#!/usr/bin/python3

"""
Title: First state model
Description: Write a python file that contains the class definition of a State
    and an instance Base = declarative_base()
Author: @a_idk scripting
"""

from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

#Base = declarative_base(metadata=Metadata())
Base = declarative_base()


class State(Base):
    """
    State class definition
    Attribs:
        id: column of autogenerated, unique int. is a primary key
        name: column of a string (max 128 characters)
        cities: rltionship with class City
    """

    __tablename__ = 'states'

    id = Column(Integer, unique=True, nullable=False, primary_key=True)
    name = Column(String(128), nullable=False)
