#!/usr/bin/python3

"""
Title: Cities in state
Description: Write a Python file similar to model_state.py named model_city.py
    that contains the class definition of a City
Author: @a_idk scripting
"""

from sqlalchemy import Column, Integer, String, ForeignKey
# from sqlalchemy.schema import Metadata
from sqlalchemy.ext.declarative import declarative_base
# from model_state import Base, State

Base = declarative_base()


class City(Base):
    """
    City class definition
    Attribs:
        id: column of autogenerated, unique int. is a primary key
        name: column of a string (max 128 characters)
        state_id: column int, is a foreign key
    """

    __tablename__ = 'cities'

    id = Column(Integer, unique=True, nullable=False, primary_key=True)
    name = Column(String(128), nullable=False)
    state_id = Column(Integer, ForeignKey('states.id'), nullable=False)
